config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get '/phones', to: 'phones#new'
  
  resources :phones
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/phone.rb
class Phone < ApplicationRecord
  has_one_attached :image

  validates :name, presence: true
  validates :model, presence: true
  validates :year, presence: true
  validates :url, presence: true
  validates :price, presence: true
  validates :seller, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @phones = Phone.all
  end
end

app/controllers/phones_controller.rb
class PhonesController < ApplicationController
  before_action :set_phone, only: [:edit, :update, :destroy, :show]

  def new
    @phone = Phone.new
  end

  def edit
  end

  def show
  end

  def create
    # byebug
    @phone = Phone.new(phone_params)
    if @phone.save
      flash[:success] = "#{@phone.name} has been successfully created."
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    if @phone.destroy
      flash[:success] = "#{@phone.name} has been successfully deleted."
      redirect_to root_path
    else
      flash[:error] = "#{@phone.name} has been not successfully deleted."
      redirect_to root_path
    end
  end

  def update
    if @phone.update(phone_params)
      flash[:success] = "#{@phone.name} has been successfully updated."
      redirect_to root_path
    else
      render :edit
    end
  end

  private
  def phone_params
    params.require(:phone).permit(:image, :name, :model, :year, :url, :price, :seller)
  end

  def set_phone
    @phone = Phone.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def seller_list
    ["Hepsiburada", "n11", "Amazon", "Trendyol", "Vatan Bilgisayar", "Diğer"]
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/phones_helper.rb
module PhonesHelper
end

app/views/home/index.slim
.ui.container
  .ui.link.cards
    - @phones.each do |p|
      .card
        .image
          = image_tag p.image, class: "single-image"
        .content
          .header
            = link_to p.name, p.url, target: "_blank"
          .meta
            = p.model
          .description
            = p.price + " "
            = icon('fas', 'lira-sign')
        .extra.content
          span.right.floated
            = p.year
          span
            i.user.icon
            = p.seller
        = link_to "Edit", edit_phone_path(p), class: "ui bottom attached blue button"
        = link_to "Delete", phone_path(p), class: "ui bottom attached red button", method: :delete
        = link_to "Show", phone_path(p), class: "ui bottom attached yellow button"

app/views/layouts/_header.slim
.ui.inverted.segment
  .ui.inverted.secondary.pointing.menu
    = link_to "Home", root_path, class: "item" 
    = link_to "New Phone", phones_path, class: "item"

app/views/layouts/application.slim
doctype html
html
  head
    title
      | SimpleRailsCrud
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    = favicon_link_tag
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = render 'layouts/header'
    = render 'shared/message'
    = yield

app/views/phones/_form.slim
= render "shared/errors", obj: obj
= form_for obj, :html => {:class => "ui form"}, url: path do |f|
  .field
    - unless obj.new_record?
      = image_tag obj.image, class: "ui medium rounded centered image"
  .field
    = f.label :image, "Image"
    = f.file_field :image
  .field
    = f.label :name, "Name"
    = f.text_field :name
  .field
    = f.label :model, "Model"
    = f.text_field :model
  .field
    = f.label :year, "Year"
    - if obj.new_record?
      = f.select :year, options_for_select(2010..Time.now.year{ |u| [u.to_i, u.to_i] }), {}, { :class => 'ui fluid dropdown' }
    - else 
      = f.select :year, options_for_select(2010..Time.now.year{ |u| [u.to_i, u.to_i] }, :selected => obj.year), {}, { :class => 'ui fluid dropdown' }
  .field
    = f.label :url, "URL"
    = f.url_field :url
  .field
    = f.label :price, "Price"
    = f.text_field :price
  .field
    = f.label :seller, "Seller"
    - if obj.new_record?
      = f.select :seller, options_for_select(seller_list.collect{ |u| [u, u] }), {}, { :class => 'ui fluid dropdown' }
    - else 
      = f.select :seller, options_for_select(seller_list.collect{ |u| [u, u] },:selected => obj.seller) {}, { :class => 'ui fluid dropdown' }
  = f.submit class: "ui button" 

app/views/phones/edit.slim
.ui.three.column.doubling.stackable.grid.container
  .column
  .column
    = render 'phones/form', path: phone_path(@phone), obj: @phone
  .column

app/views/phones/new.slim
.ui.three.column.doubling.stackable.grid.container
  .column
  .column
    = render 'phones/form', path: phones_path, obj: @phone
  .column

app/views/phones/show.slim
.ui.three.column.doubling.stackable.grid.container
  .column
  .column
    .ui.link.cards
      .card
        .image
          = image_tag @phone.image
        .content
          .header
            = link_to @phone.name, @phone.url, target: "_blank"
          .meta
            = @phone.model
          .description
            = @phone.price + " "
            = icon('fas', 'lira-sign')
        .extra.content
          span.right.floated
            = @phone.year
          span
            i.user.icon
            = @phone.seller
        = link_to "Edit", edit_phone_path(@phone), class: "ui bottom attached blue button"
        = link_to "Delete", phone_path(@phone), class: "ui bottom attached red button", method: :delete
        = link_to "Back", root_path, class: "ui bottom attached yellow button"
  .column

app/views/shared/_errors.slim
- if obj.errors.any?
  .ui.error.message.notif
    i.close.icon
    .header
      |  ERROR 
    ul.list
      - obj.errors.full_messages.each do |msg|
        li
          = msg

app/views/shared/_message.slim
- flash.each do |name, message|
  .ui.container.notif
    - if name.eql?("success")
      .ui.success.message
        i.close.icon
        .header 
          = message
    - else
      .ui.error.message
        i.close.icon
        .header 
          = message
      